[package]
name = "r2d2"
version = "0.1.0"
edition = "2021"
autotests = false
publish = false

[workspace]
members = [
    "macros",
    "utils",
    "compiled",
]

[[test]]
name = "tests"
path = "tests/01-hello_world.rs"

[dev-dependencies]
trybuild = { version = "1.0.54", features = ["diff"] }
libc = "0.2"

[dependencies]
r2d2_macros = { path = "macros" }
r2d2_utils = { path = "utils" }
