fn main() {
    #[shufflecase]
    println!("1");
    {
        #[shufflecase]
        println!("2");
        {
            #[shufflecase]
            println!("3");
            {
                #[shufflecase]
                println!("4");
                #[shufflecase]
                println!("5");
            }
            #[shufflecase]
            println!("6");
        }
        #[shufflecase]
        println!("7");
    }
    #[shufflecase]
    println!("8");
}
