fn main() {
    #[shuffle]
    println!("1");
    {
        #[shuffle]
        println!("2");
        {
            #[shuffle]
            println!("3");
            {
                #[shuffle]
                println!("4");
                #[shuffle]
                println!("5");
            }
            #[shuffle]
            println!("6");
        }
        #[shuffle]
        println!("7");
    }
    #[shuffle]
    println!("8");
}
